services:
  ngrok:
    image: ngrok/ngrok:latest
    ports:
      - "4040:4040"
    environment:
      NGROK_AUTHTOKEN: "3BjT3EXVvclUkKHxXzxQ3TfMaYV_2VBe4HherDPMo9xTM5UEj"
    command: http host.docker.internal:5129 --url=twiddly-nonadministrable-timika.ngrok-free.dev
    restart: unless-stopped
